### ISSUE TITLE
How and when did you learn programming?

### ISSUE THREAD

**Issue by zereraz** [shama/ama#12]

**Comment by shama** [comment]
I started in high school. They just opened a "new tech" high school (http://newtechhigh.org/) and I enrolled to escape the awful high school I previously attended. New Tech only had 200 students and had computers at every desk. The classrooms operated more like a business where they had open door policy and most of the school work was individual or team based projects. Although New Tech didn't really teach programming.

I originally got into programming to troll other students. The school used Lotus Notes and we discovered we could attach scripts to message sent to each other. My friends and I would create buttons that upon clicked would send school wide messages pretending to be another student. It quickly got out of control and we crashed the network many times before the administration figured out how to ban the scripts. But it was a ton of fun and I was hooked on programming.

From then on I became obsessed. I read as many books and websites as I could find. I spent a lot of my school time learning programming and my grades certainly did suffer, heh. But I didn't always have access to a computer growing up so during class was my only choice.

Besides LotusScript, JavaScript was actually my first real programming language. Every student was required to make an online portfolio and most students used Adobe ImageReady. I thought the sites ImageReady made were horrible and I decided to build mine from scratch (using notepad, of course).

On my portfolio I created a DME or Dynamic Message Editor (I am still not good at naming things). Where students could enter their own message on my portfolio. It eventually became a chat board and then a social network (before I even knew what that even was). Although it's been revised many times, it still is online today: http://kyletyoung.com/

---

So the TL;DR: I got into programming because I wanted to be the best troll in my group of friends.
