### ISSUE TITLE
What is the origin of your nick?

### ISSUE THREAD

**Issue by ungoldman** [shama/ama#8]
Your "handle," if you will. What is the origin story of `shama`?

**Comment by shama** [comment]
`shama` is short for `shamabaghodia`.

A long time ago I was an art student. I played around with inventing words and making posters intentionally ambiguous. I liked hearing the different interpretations of words I created and would put copies up around campus with no explanation:
![shama](https://cloud.githubusercontent.com/assets/99604/8807673/fc013088-2f92-11e5-9629-c45dff7b8fd5.jpg)
For some reason that one stuck and became the alias I used for other art projects.

A little bit later I got into online gaming, mostly Counter-Strike. My friends and I started a gaming clan in which I used the name `[xes]shamabaghodia`. Here was the website for it: https://web.archive.org/web/20030813074907/http://www.xesclan.org/

Everyone just called me "shama" for short. Later I found out that "shama" means a beautiful girl but by that time, people seem to prefer calling me shama and not by my real name. It even continues today, at work my user in slack is `@kyle` but my co-workers still often mistakenly use `@shama`. It's weird because I was introduced to them as "Kyle" but for some reason "shama" is more memorable. I've noticed this at meetups and conferences too.

So now I just own it and respond to being called "shama" the same as if you said "Kyle."
